// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Ubique.DataAccess.Data;

#nullable disable

namespace Ubique.DataAccess.Migrations
{
	[DbContext(typeof(ApplicationDbContext))]
    [Migration("20231016152204_AddingHierarchyToFaucets")]
    partial class AddingHierarchyToFaucets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ubique.Models.Faucet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpoutLength")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faucets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Paini",
                            Color = "Metal",
                            DisplayOrder = 1,
                            Name = "ATOMIX 3.0",
                            SpoutLength = "30mm",
                            SubType = "Monoleva",
                            Type = "Lavabo"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "NOBILI",
                            Color = "Metal",
                            DisplayOrder = 2,
                            Name = "Svastun",
                            SpoutLength = "25mm",
                            SubType = "Due maniglie",
                            Type = "Bidet"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Paini",
                            Color = "Metal",
                            DisplayOrder = 3,
                            Name = "ATOMIX 11.0",
                            SpoutLength = "30mm",
                            SubType = "Termostatici",
                            Type = "Lavabo"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "NOBILI",
                            Color = "Metal",
                            DisplayOrder = 4,
                            Name = "ATOMIX 4.5",
                            SpoutLength = "30mm",
                            SubType = "Monoleva",
                            Type = "Lavabo"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "NOBILI",
                            Color = "Metal",
                            DisplayOrder = 5,
                            Name = "HyperX",
                            SpoutLength = "25mm",
                            SubType = "",
                            Type = "Bidet"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Paini",
                            Color = "Metal",
                            DisplayOrder = 6,
                            Name = "JUMPER",
                            SpoutLength = "30mm",
                            SubType = "",
                            Type = "Cascata"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
