// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ubique.Data;

#nullable disable

namespace Ubique.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231016145453_ChangeBathToFaucetAndSeedDb")]
    partial class ChangeBathToFaucetAndSeedDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ubique.Models.Faucet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpoutLength")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Faucets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Paini",
                            Color = "Metal",
                            DisplayOrder = 1,
                            Name = "ATOMIX 3.0",
                            SpoutLength = "30mm",
                            Type = "Lavabo"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "NOBILI",
                            Color = "Metal",
                            DisplayOrder = 2,
                            Name = "Svastun",
                            SpoutLength = "25mm",
                            Type = "Bidet"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Paini",
                            Color = "Metal",
                            DisplayOrder = 3,
                            Name = "ATOMIX 11.0",
                            SpoutLength = "30mm",
                            Type = "Rubinetteria Lavabo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
